=== pbonato3/SitoPopulon/database/characters.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="characters" type="characters"/>

	<xs:complexType name="characters">
		<xs:sequence>
			<xs:element name="character" type="character" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="character">
		<xs:sequence>
			<xs:element name="name" type="xs:string" />
			<xs:element name="race" type="raceT" />
			<xs:element name="sex" type="sexT" />
			<xs:element name="age" type="xs:positiveInteger" />
			<xs:element name="body" type="stat" />
			<xs:element name="mind" type="stat" />
			<xs:element name="heart" type="stat" />
			<xs:element name="bio" type="xs:string" />
		</xs:sequence>
		<xs:attribute name="id" type="xs:positiveInteger" use="required" />
	</xs:complexType>
	
	<xs:simpleType name="sexT">
		<xs:restriction base="xs:string">
			<xs:enumeration value="M" />
			<xs:enumeration value="F" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="raceT">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Akquor" />
			<xs:enumeration value="Elfo" />
			<xs:enumeration value="Ur-Aluk" />
			<xs:enumeration value="Troll" />
			<xs:enumeration value="Mustelan" />
			<xs:enumeration value="Tesserian" />
			<xs:enumeration value="Spyrian" />
			<xs:enumeration value="Nano" />
			<xs:enumeration value="Umano" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="stat">
		<xs:sequence>
			<xs:element name="ability" type="abilityT" maxOccurs="unbounded" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="value" type="xs:integer" />
	</xs:complexType>
	
	<xs:complexType name="abilityT">
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="level" type="levelT" />
	</xs:complexType>
	
	<xs:simpleType name="levelT">
		<xs:restriction base="xs:integer">
			<xs:enumeration value="0" />
			<xs:enumeration value="1" />
			<xs:enumeration value="2" />
			<xs:enumeration value="3" />
			<xs:enumeration value="4" />
			<xs:enumeration value="5" />
		</xs:restriction>
	</xs:simpleType>	
	
</xs:schema>

=== pbonato3/SitoPopulon/database/characters.xml
<?xml version="1.0" encoding="UTF-8"?>
<characters xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="characters.xsd">
<character id="6">
	<name>ciccioBello</name>
	<race>Akquor</race>
	<sex>male</sex>
	<age>24</age>
	<body value="9">
		<ability name="Rutto Spaziale" level="5"/>
	</body>
	<mind value="23">
	</mind>
	<heart value="123">
	</heart>
	<bio/>
</character>
<character id="5">
	<name>Gattivo</name>
	<race>Tesserian</race>
	<sex>male</sex>
	<age>2</age>
	<body value="25">
		<ability name="Dormire" level="5"/>
		<ability name="Cagare in giro per casa" level="1"/>
		<ability name="Vomitare in giro per casa" level="1"/>
	</body>
	<mind value="5">
		<ability name="Fare il mona" level="3"/>
	</mind>
	<heart value="20">
		<ability name="Coccole" level="4"/>
	</heart>
	<bio>Un gatto</bio>
</character>
<character id="4">
	<name>Toni</name>
	<race>Umano</race>
	<sex>M</sex>
	<age>82</age>
	<body value="25">
		<ability name="Ombre de matina" level="5"/>
		<ability name="Graspe dopo un boto" level="4"/>
	</body>
	<mind value="10">
		<ability name="Guardare i lavori" level="4"/>
	</mind>
	<heart value="40">
		<ability name="Ai me tempi..." level="5"/>
	</heart>
	<bio>Un vecio contadin</bio>
</character>


<character id="2">
	<name>Sanjo Rabaton jr.</name>
	<race>Troll</race>
	<sex>M</sex>
	<age>35</age>
	<body value="40">
		<ability name="Griliare salsicce" level="2"/>
		<ability name="Griliare costine" level="3"/>
		<ability name="Griliare poenta" level="3"/>
	</body>
	<mind value="0">
	</mind>
	<heart value="10">
		<ability name="Far sagra" level="2"/>
	</heart>
	<bio>
		Nato pa' far sagra e star su pa'ea piastra.
	</bio>
</character>

<character id="3">
	<name>Babba Lea</name>
	<race>Umano</race>
	<sex>F</sex>
	<age>21</age>
	<body value="20">
		<ability name="Griliare salsicce" level="2"/>
	</body>
	<mind value="0">
	</mind>
	<heart value="10">
		<ability name="Far sagra" level="2"/>
	</heart>
	<bio>
		Nato pa' far sagra e star su pa'ea piastra.
	</bio>
</character>

</characters>
