=== pbonato3/SitoPopulon/database/news.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="notizie" type="news_group" />

	<xs:complexType name="news_group">
		<xs:sequence>
			<xs:element name="notizia" type="news" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="news" mixed="true">
		<xs:sequence>
			<xs:element name="titolo" type="xs:string" />
			<xs:element name="data" type="xs:date" minOccurs="0"/>
			<xs:element name="ora" type="xs:time" minOccurs="0"/>
			<xs:element name="luogo" type="xs:string" minOccurs="0"/>
			<xs:element name="descrizione" type="xs:string" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:positiveInteger" use="required" />
	</xs:complexType>

	
</xs:schema>

=== pbonato3/SitoPopulon/database/news.xml
<?xml version="1.0" encoding="UTF-8"?>
<notizie xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="news.xsd">
	<notizia>
		<titolo> Notizia 1 </titolo>
		<data> 2016-04-27 </data>
		<luogo> Luogo 1 </luogo>
	</notizia>
	<notizia>
		<titolo> Notizia 2 </titolo>
		<data> 2016-04-28 </data>
		<ora> 19:20:00 </ora>
		<luogo> Luogo 2 </luogo>
	</notizia>
</notizie>
